site:
  title: OCS Training
  #url: https://red-hat-storage.github.io/ocs-training
  url: https://mid998.github.io/ocs-training
  start_page: training::index.adoc
  robots: allow
  keys:
    google_analytics: 'G-LGCEEZGN54'
content:
  sources:
  - url: https://github.com/mid998/ocs-training.git
  # - url: .
    branches: [master]
    start_paths: [training]
    edit_url: '{web_url}/edit/{refname}/{path}'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ui
# output:
  # clean: true
  # dir: ./site
